- .github/workflows/ci.yaml
- lib/charms/dp_pgbouncer_operator/v0/pgb.py
- src/charm.py
- tests/unit/data/test_userlist.txt
- tests/unit/test_pgb.py
- tox.ini
This PR creates a charm library that abstracts some common functions across the pgbouncer charms, which will be published to the /edge channel of the pgbouncer-operator charm on charmhub once implemented. 
The functions this library abstracts are as follows:
- Generating passwords
- Generating config files 
These will obviously expand over time as the charms become more fully featured.
[Jira Ticket](https://warthogs.atlassian.net/browse/DPE-48?atlOrigin=eyJpIjoiZjY4ZmNmZWI5YjhhNDNjMWIzMjE5Mjg2YWNiZDA0YzAiLCJwIjoiaiJ9)
> DPE-48 Adding basic charm library

- .github/pull_request_template.md
This repo has no PR templates, making it easy for PR authors to forget necessary information such as context or testing. 
[JIRA ticket](https://warthogs.atlassian.net/browse/DPE-107?atlOrigin=eyJpIjoiYWUyMmJiNTZiNTc2NDI1NGE5ZWYzNzI1YmMxNTdlMTAiLCJwIjoiaiJ9)
Add a PR template that adds useful sections to PRs moving forward. 
This template differs slightly from [Shayan's proposed template](https://github.com/canonical/mysql-k8s-operator/pull/70). My reasoning for changing the template in this repo without propagating my feedback to the original PR is as follows:
- I want to start using PR templates as soon as possible. It's easy to endlessly discuss process, but we won't fully understand what's useful information and what's a chore until we try it. 
- I'd prefer for these standards to be …
> DPE-107 Add Pr Template 

- .gitignore
- actions.yaml
- charmcraft.yaml
- config.yaml
- lib/charms/dp_pgbouncer_operator/v0/pgb.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- tests/integration/test_charm.py
- tests/unit/data/test.ini
- tests/unit/data/test_bad_db.ini
- tests/unit/data/test_bad_dbname.ini
- tests/unit/data/test_no_dbs.ini
- tests/unit/data/test_no_logfile.ini
- tests/unit/data/test_no_pidfile.ini
- tests/unit/data/test_reserved_db.ini
- tests/unit/data/test_userlist.txt
- tests/unit/test_charm.py
- tests/unit/test_pgb.py
- tox.ini
[Jira Ticket](https://warthogs.atlassian.net/browse/DPE-105?atlOrigin=eyJpIjoiZmVkZjk3MTcxYzM0NGJkMDg1NTU0NTQ5YjY1YWVlNWIiLCJwIjoiaiJ9)
This PR implements a class in the pgb charm library that can handle pgbouncer.ini config files, including parsing, editing, and writing. The existing implementation is a placeholder that implements the bare minimum for the pgbouncer application to come online, whereas the proposed implementation is capable of making use of the entire [pgbouncer config spec](https://www.pgbouncer.org/config.html). 
This class implements a mutablemapping that's copied from a [ConfigParser](https://docs.python.org/3/library/configparser.html) object, allowing config options to be accessed and modified dictionary-style, as well as providing some basic validation. The reason …
> DPE-105 Adding pgbouncer.ini Config Management. 

- src/relations/db.py
- tests/unit/relations/test_db.py
When pointing to readonly endpoints, pgbouncer would just pick a random standby node and point to that. This PR updates the standby node in the pgb config to point to all postgres standby nodes, switching between them in a round robin. 
[docs](https://www.pgbouncer.org/config.html#host)
- Unit tests have been updated, all integration tests currently pass
> updated readonly endpoints

- lib/charms/pgbouncer_k8s/v0/pgb.py
- requirements.txt
- tests/unit/relations/test_backend_database.py
- tests/unit/relations/test_db.py
- tests/unit/test_charm.py
Ops v1.5.3 adds better typing support. This happens to break a few of my existing tests that weren't correctly typed. 
- Fix unit tests broken by ops v1.5.3.
> Fixed typing errors in ops v1.5.3

- lib/charms/pgbouncer_k8s/v0/pgb.py
- src/relations/peers.py
- tests/integration/helpers/helpers.py
- tests/integration/helpers/postgresql_helpers.py
- tests/integration/relations/test_backend_database.py
- tox.ini
Jira issue: [DPE-561](https://warthogs.atlassian.net/browse/DPE-561)
PgBouncer must use encrypted connections when PostgreSQL has TLS enabled. 
* The `server_tls_sslmode = prefer` parameter makes PgBouncer use TLS when it is enabled on PostgreSQL.
* The `get_backend_relation` helper method was't used in any place, so it was removed.
* Som helper methods (on `tests/integration/relations/test_backend_database.py`) were copied from the PostgreSQL charm integration tests to check that an encrypted connection is established between PgBouncer and PostgreSQL.
* Enable TLS encrypted connection between PgBouncer and PostgreSQL.
* `tests/integration/relations/test_backend_database.py` contains an additional integration test that checks that TLS is being used.
> Add TLS encryption between PgBouncer and PostgreSQL

- src/relations/db.py
- tests/unit/relations/test_db.py
Reverts canonical/pgbouncer-operator#24
The feature that this PR relies on is only implemented in pgbouncer version 1.17. This'll be re-implemented once the pgbouncer snap is available
> Revert "updated readonly endpoints"

- src/relations/pgbouncer_provider.py
- tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
- tests/integration/relations/test_peers.py
Jira ticket: [DPE-1234](https://warthogs.atlassian.net/browse/DPE-1234)
The PgBouncer charm failed when the other charm haven't requested any extra user roles (so the field is None and due to that it cannot be iteraded). It was happening when relating to the data-integrator and specifying only it's required config (database name), but it would happen with any other charm that don't request extra user roles through the relation.
Fixed that by using an empty value instead of none, to be consistent with the check the PgBouncer charm make.
It's the same that was implemented on https://github.com/canonical/pgbouncer-k8s-operator/pull/36.
Fix relatior error when extra user roles field has no value.
Added a test where the charm is related to the data integrator.
[DPE-1234]: …
> Fix relatior error when extra user roles field has no value

- tests/integration/relations/test_peers.py
- tox.ini
* [DPE-1162](https://warthogs.atlassian.net/browse/DPE-1162)
* Update libjuju to latest v2
* Unpin flake8
[DPE-1162]: https://warthogs.atlassian.net/browse/DPE-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update flake8 and libjuju

- src/relations/backend_database.py
- tests/unit/relations/test_backend_database.py
Seems like the update to jammy for postgresql switch the default password hashing. This forces md5 mechanism for the pgb auth user.
> Revive pgb

- src/charm.py
* [DPE-1514](https://warthogs.atlassian.net/browse/DPE-1514)
* Sets the workload version to what Pgbouncer reports as it's version
* Essentially the same thing as [PR#67](https://github.com/canonical/pgbouncer-k8s-operator/pull/67) for K8S
[DPE-1514]: https://warthogs.atlassian.net/browse/DPE-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Set workload version to PGB version

- src/constants.py
Security scan detected outdated packages in the charmed-postgresql snap:
```
Revision r50 (amd64; channels: 14/edge)
* libpq5: 6104-1
* postgresql-14: 6104-1
* postgresql-client-14: 6104-1
* postgresql-plpython3-14: 6104-1
```
Rebuild the snap and updated the held revision
> Refresh snap due to packages update

- metadata.yaml
- src/constants.py
- tests/integration/helpers/helpers.py
- tests/integration/relations/test_backend_database.py
* The PGB charm will break if having multiple backend database relations
* The PGB charm should subordinate to only a single principle
* Snapped psql needs to make network connections
* Limit interfaces where we want a one-to-one relationship
* Update to snap revision with fixed psql
* Remove a workaround for forcing the series of charms used for testing (fixed in libjuju)
> [DPE-2049][DPE-2050] Interface limits and revision update

- src/constants.py
Security scan report:
```
Revision r61 (amd64; channels: 14/edge)
* libc-ares2: 6164-1
```
Rebuild and update snap
> Update revision due to outdated packages

- charmcraft.yaml
- lib/charms/operator_libs_linux/v2/snap.py
- poetry.lock
- pyproject.toml
- renovate.json
- requirements.txt
- src/charm.py
- src/constants.py
- src/relations/db.py
- tests/integration/relations/pgbouncer_provider/application-charm/metadata.yaml
- tests/integration/relations/pgbouncer_provider/application-charm/requirements.txt
- tests/integration/relations/pgbouncer_provider/application-charm/src/charm.py
- tests/integration/relations/test_db.py
- tests/unit/test_charm.py
Pgbouncer would block when a legacy relation requests  extensions even if they are enabled in the backend Postgresql DB
* Check for extensions in the backend relation and block accordingly
* Updated snap charm lib
* Since the subordinate unit will be removed on broken relation, there's no need to recheck extensions blocking
> [DPE-2055] PGB extensions suport

- poetry.lock
- requirements.txt
Looks like charmcraft 2.4.1 doesn't fail with dependencies duplicated in PYDEPS.
> [MISC] Restore duplicated dependencies in requirements.txt

- metadata.yaml
* documentation on Discourse was missing
* metadata.yaml was outdated (missing lings, outdated year, wrong summary, etc)
We are preparing the charm for release to stable and need to
generate all the necessary documentation/links on https://charmhub.io/pgbouncer
* update metadata.yaml to match pgbouncer-k8s concepts
* add Discourse documentation Overview page
* Also sync all SQL charms layout in metadata.yaml
> DPE-2753 Add Discourse documentation + update metadata.yaml

- src/constants.py
Outdated packages:
````
Revision r96 (amd64; channels: 14/edge)
* libldap-2.5-0: 6616-1
* libmysqlclient21: 6615-1
````
> [MISC] Update snap due to outdated packages

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- poetry.lock
- pyproject.toml
- src/charm.py
- src/constants.py
- src/relations/backend_database.py
- src/relations/db.py
- src/relations/peers.py
- src/relations/pgbouncer_provider.py
- tests/unit/relations/test_backend_database.py
- tests/unit/relations/test_peers.py
- tests/unit/test_charm.py
Update peer secrets implementation to be up to date with other PG charms
> [DPE-3184] Update secrets implementation

- src/charm.py
- src/relations/peers.py
- tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Peer secrets were set as peer data. Copy of https://github.com/canonical/pgbouncer-k8s-operator/pull/212
> [MISC] Fix secret keys

- src/charm.py
- src/upgrade.py
- tests/unit/test_upgrade.py
Update rendered a blank config and relied on perpetual peer changed to refresh the configs.
> [DPE-3535] Rerender config from secrets during upgrade

- src/charm.py
- src/constants.py
- tests/unit/test_charm.py
Copy of https://github.com/canonical/postgresql-operator/pull/345
Use a different snap depending on CPU architecture.
> [MISC] Architecture specific snap revision

- src/charm.py
- tests/integration/helpers/postgresql_helpers.py
- tests/integration/test_charm.py
> [DPE-3602] Charm restart

- tests/integration/test_upgrade_from_stable.py
Use stable charm for upgrade test, since it now works with Juju 3.1.7
> [MISC] Switch stable upgrade test branch

- .github/workflows/ci.yaml
- tests/integration/helpers/helpers.py
- tests/integration/test_subordinates.py
Copy subordinate charms test from the Postgresql VM charm.
> [DPE-3658] Add subordinate charms test

- src/relations/backend_database.py
Auth query functions are not readded when backend rerelates
Collect existing client rel dbs and add or remove auth_query function on backend rel events
> [DPE-4221] Recreate auth_query on backend rerelation

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/db.py
- src/relations/pgbouncer_provider.py
- tests/integration/relations/pgbouncer_provider/helpers.py
- tests/unit/relations/test_db.py
- tests/unit/relations/test_pgbouncer_provider.py
Cannot drop db objects when rerelating to pgbouncer
* Pass relations to create_database
Port of https://github.com/canonical/pgbouncer-k8s-operator/pull/287
> [DPE-1454] Update database ownership

- actions.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/operator_libs_linux/v2/snap.py
- src/charm.py
- templates/pgb_config.j2
- tests/unit/test_charm.py
Collect read only dbs from the backend postgresql when wildcard dbs are enabled.
Split off of https://github.com/canonical/pgbouncer-operator/pull/210 for easier review.
> [DPE-3927] Collect readonly dbs

- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/tempo_k8s/v2/tracing.py
- src/charm.py
- tests/unit/test_charm.py
Exit read only db collection if unable to connect to the backend database.
Example failure: https://github.com/canonical/postgresql-bundle/actions/runs/9537877087/job/26286454688
> [MISC] Don't fail when collecting readonly dbs

- lib/charms/tempo_k8s/v1/charm_tracing.py
- src/charm.py
- src/relations/peers.py
- src/relations/pgbouncer_provider.py
- tests/unit/relations/test_pgbouncer_provider.py
> Sync configs between units

- lib/charms/postgresql_k8s/v0/postgresql.py
- tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Scale up tests didn't wait for PGB to be up and running before checking the connection through the test app.
> [MISC] Wait for PGB to idle when scaling up

- lib/charms/data_platform_libs/v0/upgrade.py
- src/charm.py
- src/relations/peers.py
- src/upgrade.py
- tests/integration/relations/pgbouncer_provider/helpers.py
- tests/integration/relations/pgbouncer_provider/test_data_integrator.py
- tests/integration/test_upgrade.py
- tests/integration/test_upgrade_data_integrator.py
- tests/unit/relations/test_peers.py
- tests/unit/test_charm.py
* Fixing new snap install failure due to writing to SNAP_DATA prematurely
* Fixing upgrade not triggering on a single unit
Lib changes should be upstreamed 
Fixes https://github.com/canonical/pgbouncer-operator/issues/267
> [DPE-4799] Fix upgrade bugs when switching charms

- src/charm.py
- tests/unit/test_charm.py
When cohosting Pgbouncer and Postgresql (like in maas-anvil) the pgbouncer charm will be unable to recreate the `psql` alias and print an error traceback in the logs. Since this is expected behaviour, the log is donwgraded to warning
> [MISC] Suppress alias creation error

- .github/workflows/ci.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- src/relations/backend_database.py
- tests/unit/relations/test_backend_database.py
* Revert scheduled test move
* Fix for transient model error seen in CI
> [MISC] Move scheduled tests

- pyproject.toml
Added in poetry 1.8
(metadata unused since charm is not a Python package)
> Use poetry package-mode=false

- src/relations/backend_database.py
- tests/unit/test_upgrade.py
Handles uncaught exception:
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/./src/charm.py", line 999, in <module>
main(PgBouncerCharm)
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/venv/ops/main.py", line 553, in main
manager.run()
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/venv/ops/main.py", line 529, in run
self._emit()
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/venv/ops/main.py", line 518, in _emit
_emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
event_to_emit.emit(*args, **kwargs)
File "/var/lib/juju/agents/unit-pgbouncer-2/charm/venv/ops/framework.py", line 347, in emit
framework._emit(event)
File …
```
> [DPE-5338] Handle Secret permission error

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Clean test builds and clean release builds conflict with each other:
https://github.com/canonical/pgbouncer-operator/actions/runs/11051924076/job/30702900672
> [MISC] Disable conflicting build

- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/charm.py
- src/relations/pgbouncer_provider.py
- tests/unit/relations/test_pgbouncer_provider.py
* Update libs
* Removes an OPS import warning
* Fixes wrong emission of `database_created` due to creating the secret before the requirer sets the requested database (data-integrator)
> [DPE-5564] Don't set secrets until db is set

- src/constants.py
Remove tracking of snap channel for the charmed-postgresql snap
> [MISC] Stop tracking channel for held snaps

- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- pyproject.toml
- src/charm.py
- tests/unit/conftest.py
We are unable to relay traces through grafana-agent yet due to https://github.com/canonical/grafana-agent-operator/issues/195. However, in the meantime, we would like to update the charm tracing libs as they now reside in tempo_coordinator_k8s
Update location of charm tracing libs
> [DPE-5312] Retrieve charm tracing libs from tempo_coordinator_k8s instead

- lib/charms/pgbouncer_k8s/v0/pgb.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- templates/pgb_config.j2
PGB doesn't load balance the read only databases when multiple read only backend units are available
Add `server_round_robin` to enable round robin connections when multiple hosts are available.
> [DPE-5613] Enable round robin connections to read only backend nodes

- .github/workflows/release.yaml
Release flow fails due to mismatch of build jobs in the CI and release flow [E.g.](https://github.com/canonical/pgbouncer-operator/actions/runs/11742113069/job/32712167513):
```
ValueError: Cannot resolve multiple versions found for 
reusable_workflow_file_name='build_charm.yaml' 
reusable_workflow_repository='canonical/data-platform-workflows':
• v23.0.4 (60f088b7f0f967a8e35d45339f5123a6e74786f7)
• self-hosted-builders (a8d92a8c9200c0e491ce608705c8adff0ad70b87)
```
> [MISC] Use the same build job in release and ci workflows

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/data_models.py
- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- tests/integration/helpers/helpers.py
- tests/integration/relations/pgbouncer_provider/test_data_integrator.py
- tests/integration/relations/pgbouncer_provider/test_data_integrator_ha.py
- tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
- tests/integration/relations/test_backend_database.py
- tests/integration/relations/test_db.py
- tests/integration/relations/test_peers.py
- tests/integration/test_charm.py
- tests/integration/test_config.py
- tests/integration/test_subordinates.py
- tests/integration/test_upgrade.py
- tests/integration/test_upgrade_data_integrator.py
- tests/integration/test_upgrade_from_stable.py
* Deploy subordinates with 0 units instead of None
> [MISC] Update libs

- lib/charms/postgresql_k8s/v0/postgresql.py
- src/charm.py
- src/relations/pgbouncer_provider.py
- tests/unit/relations/test_pgbouncer_provider.py
This PR contains a slight refactor to sync code with PostgreSQL VM / K8s operator codebases.
Changes:
- Start leveraging PostgreSQL lib `PERMISSIONS_GROUP_ADMIN` constant.
- Start passing PostgreSQL lib create-user `extra_user_roles` argument  as a list.
> [MISC] Sanitize PostgreSQL extra-user-roles arg

- concierge.yaml
Default branch for lxd is 5.2, while latest is 6.3.
> [MISC] Use latest/stable lxd
