canonical/pgbouncer-operator

metadata.yaml, src/relations/db.py, tests/integration/test_charm.py, tests/unit/relations/test_db.py
Jira issue: [DPE-515](https://warthogs.atlassian.net/browse/DPE-515)
Metadata name needs to reflect registered name to enable store release.
=> Metadata name needs to reflect registered name

.github/workflows/ci.yaml, .github/workflows/release.yaml, src/relations/backend_database.py
Reuse CI pipeline in release.yaml.
=> Ci cleanup

.github/workflows/ci.yaml, .github/workflows/release.yaml
Added workflow-call to CI.yaml, allowing it to be called from release.yaml. While I'm working on the CI, I also updated LXD and some github actions.
=> fix release workflow

.github/workflows/ci.yaml, .github/workflows/release.yaml, charmcraft.yaml, lib/charms/data_platform_libs/v0/database_provides.py, lib/charms/pgbouncer_k8s/v0/pgb.py, lib/charms/postgresql_k8s/v0/postgresql.py, requirements.txt, src/constants.py, src/relations/backend_database.py
Preliminary updates for the new client relation.
- Updated postgres lib, with minor compatibility updates
- added provider lib
- Version updates
=> Add client relation libs, and other busywork

src/pgbouncer@.service, tests/integration/helpers/helpers.py, tests/integration/test_charm.py
Minor cleanup to pgbouncer start-service test.
=> updated service test

.github/workflows/ci.yaml, lib/charms/data_platform_libs/v0/database_provides.py, lib/charms/data_platform_libs/v0/database_requires.py, lib/charms/operator_libs_linux/v0/apt.py, lib/charms/pgbouncer_k8s/v0/pgb.py, lib/charms/postgresql_k8s/v0/postgresql.py, requirements.txt, src/relations/backend_database.py, tests/unit/relations/test_backend_database.py, tox.ini
* [DPE-1160](https://warthogs.atlassian.net/browse/DPE-1160)
* Update ops framework
* Copy over check lib and ignore text files from the postgresql K8S charm to ci.yaml
* Housekeeping
[DPE-1160]: https://warthogs.atlassian.net/browse/DPE-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update ops framework and charm libs

.github/workflows/release.yaml
* Broke the release workflow with the previous PR
* Remove check libs from the release workflow
* pass the secrets to the ci flow
=> Fix release on main branch

lib/charms/operator_libs_linux/v1/systemd.py, src/relations/pgbouncer_provider.py
Adding the database field in the provider side. This is to follow the interface signature change https://github.com/canonical/charm-relation-interfaces/pull/43
=> [MISC] Add database field in the provider-side databag

src/constants.py
Security scan report:
```
Revision r60 (amd64; channels: 14/edge)
* python3-requests: 6155-1
```
Rebuild and update snap
=> Update revision due to outdated packages

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/grafana_agent/v0/cos_agent.py, lib/charms/operator_libs_linux/v2/snap.py, src/charm.py, templates/logrotate.j2, templates/pgbouncer.service.j2, templates/prometheus-exporter.service.j2, tests/integration/relations/pgbouncer_provider/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py, tests/integration/relations/test_db.py, tests/integration/test_charm.py, tests/unit/test_charm.py
No log rotation is done with PGB logs
* Add scaffolds for using logrotate
* Add basic logrotate configuration
* Updated charm libs
=> [DPE-1757] Log rotation

src/constants.py
Updating snap due to outdated dependencies:
```
Revision r66 (amd64; channels: 14/edge)
* libllvm14: 6258-1
```
=> [MISC] Update snap

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, poetry.lock, pyproject.toml, renovate.json, src/relations/db.py, tests/integration/helpers/helpers.py, tests/integration/helpers/postgresql_helpers.py, tests/integration/relations/test_backend_database.py, tests/integration/relations/test_db.py, tests/integration/test_charm.py, tox.ini
We should run integration tests against both juju 3 and juju 2
* Add support for running integration test on both juju versions
=> [DPE-1761] Juju 3

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/constants.py, src/relations/backend_database.py, src/relations/db.py, src/relations/peers.py, tests/unit/relations/test_backend_database.py, tests/unit/test_charm.py
Charm doesn't use secrets for internal sensitive values
* Use Juju secrets instead of peer data if available
* Updated charm libs
=> [DPE-1765] Juju 3 peer secrets

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/relations/test_backend_database.py
Postgresql log location changed.
Update the test to look at the right place for TLS connection.
=> [MISC] Fix backend tests

.github/workflows/ci.yaml, actions.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/data_platform_libs/v0/upgrade.py, lib/charms/postgresql_k8s/v0/postgresql.py, metadata.yaml, poetry.lock, pyproject.toml, requirements.txt, src/charm.py, src/dependency.json, src/relations/peers.py, src/upgrade.py, tests/integration/helpers/helpers.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/relations/test_peers.py, tests/integration/test_charm.py, tests/integration/test_upgrade.py, tests/unit/test_charm.py, tests/unit/test_upgrade.py, tox.ini
=> [DPE-1770] Minor version upgrades

.github/workflows/ci.yaml, .github/workflows/lib-check.yaml, .github/workflows/release.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/postgresql_k8s/v0/postgresql.py, poetry.lock, pyproject.toml, tests/integration/helpers/postgresql_helpers.py, tests/integration/relations/test_backend_database.py
A number of tests drifted underneath the repo
* Fix failing tests
* Split off check lib
=> [DPE-2804] Tweak tests

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/grafana_agent/v0/cos_agent.py, lib/charms/postgresql_k8s/v0/postgresql.py, src/constants.py
=> [DPE-3040] Update snap

tests/integration/conftest.py, tests/integration/helpers/__init__.py, tests/integration/helpers/ha_helpers.py, tests/integration/helpers/postgresql_helpers.py, tests/integration/test_upgrade.py, tests/integration/test_upgrade_from_stable.py
Replace the rudimentary upgrade test of the charm upgrading over itself with a copy of the more comprehensive tests in the PG charm
=> [DPE-3256] Upgrade test

lib/charms/operator_libs_linux/v2/snap.py
Similar to https://github.com/canonical/postgresql-operator/pull/438
=> [MISC] Update operator_libs_linux library to version 2.5

lib/charms/data_platform_libs/v0/data_interfaces.py, src/charm.py, tests/unit/test_charm.py
Some tests were executed with incorrect mocks. Thus we had "fake" green results. The latest `data-interfaces` changes highlight on that.
Also some tests (suffering of the above) were irrelevant for PGbouncer and could be removed.
=> data_platform_libs update

LICENSE
This reverts commit 2a3136a9309839c2cb219e6cb492367d7105bef0.
=> [DPE-4423] Revert "update LICENSE file (#231)"

lib/charms/tempo_k8s/v1/charm_tracing.py, src/charm.py, src/constants.py, src/relations/pgbouncer_provider.py, src/upgrade.py, templates/pgbouncer.service.j2, templates/prometheus-exporter.service.j2, tests/unit/relations/test_pgbouncer_provider.py, tests/unit/test_charm.py, tests/unit/test_upgrade.py
* Updating charm libs
* Adding issues noticed during wildcard db implementation in k8s
* Switching to the separate pgb snap
=> [DPE-4261] Switch to split snap

lib/charms/postgresql_k8s/v0/postgresql.py, poetry.lock, pyproject.toml, tests/integration/relations/test_db_admin.py
* Make sure the charm has jinja2 installed
* Update libs
* Fix the Landscape test failures
=> [DPE-4816] Add jinja2 as a dependency

.github/renovate.json5, .github/workflows/ci.yaml, lib/charms/tempo_k8s/v1/charm_tracing.py
Use reusable presets for Juju version pins
=> [MISC] Switch to resusable presets

.github/workflows/ci.yaml
Switch Juju agent pins to be compatible with PG juju requirements
=> [DPE-4811] Run CI on 3.4.4

lib/charms/postgresql_k8s/v0/postgresql.py
=> [MISC] Update charm libs

lib/charms/tempo_k8s/v2/tracing.py, tests/integration/helpers/ha_helpers.py, tests/integration/helpers/helpers.py, tests/integration/relations/pgbouncer_provider/helpers.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Switch test-app interface from `first-database` to `database`
Update charm libs
=> [MISC] Switch test app interface

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/tempo_k8s/v1/charm_tracing.py
=> [MISC] Bump libs

src/charm.py, src/relations/peers.py, src/relations/pgbouncer_provider.py, tests/unit/relations/test_pgbouncer_provider.py
Should fix issues happening in the data-integrator tests: https://github.com/canonical/data-integrator/actions/runs/10625135518/job/29454710269#step:28:350
=> [MISC] Fix missing IP errors

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/tempo_k8s/v2/tracing.py
* Temporarily disable cached builds until https://github.com/canonical/charmcraftcache-hub/issues/111 can be resolved
* Bump libs
=> [MISC] Disable cached builds

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py
=> [DPE-5642] Re-enable cached builds

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py
* Switch integration tests to self hosted runners
=> [DPE-5642] Integration tests on self-hosted runners

.github/workflows/ci.yaml, .github/workflows/release.yaml
Disable self-hosted packing and test runs after a week of testing.
=> [DPE-5642] Disable self hosted packing and integration tests

.github/workflows/ci.yaml
=> [MISC] Switch back to Github runners

src/grafana_dashboards/pgbouncer-metrics.json
General polishings for our Pgbouncer dashboard, fixes #230. More details on comments.
=> [DPE-4390] Polish COS dashboard

.github/workflows/release.yaml
=> Fix comment

.github/workflows/ci.yaml, charmcraft.yaml, tests/integration/conftest.py, tests/integration/relations/pgbouncer_provider/test_data_integrator.py, tests/integration/relations/pgbouncer_provider/test_data_integrator_ha.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py, tests/integration/test_subordinates.py, tests/integration/test_upgrade_data_integrator.py
=> [MISC] Add noble base

.github/workflows/ci.yaml, tests/integration/test_subordinates.py, tests/integration/test_upgrade.py
* Re-enable cached builds
* Set upgrade series
=> [MISC] Reenable cached build

.github/renovate.json5
Missed a bracket when disabling tenacity updates.
=> [MISC] Fix renovate config

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/relations/pgbouncer_provider.py, tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
Forgot to update the read only uris with the sockets.
Also updating charm libs.
=> [DPE-4683] Set read only host

pyproject.toml, src/charm.py, tests/unit/test_charm.py, uv.lock
* Use new way to check Juju version
* Update uv lock
=> [MISC] Remove Juju version warning

lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/postgresql_k8s/v1/postgresql.py
Sync up `postgresql` lib with trigger removal.
=> [DPE-7594] Update libs with latest pg_hba changes
